# Generated by Django 6.0 on 2026-02-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_alter_graph_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='graph_data',
            new_name='nodes',
        ),
    ]
