server {
    listen 80;
    server_name localhost;

    # 1. Фронтенд (Статика)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Важно для React Router!
    }

    # 2. Бэкенд API
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }

    # 3. Админка Django
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    # 4. Статика Django (админка и т.д.)
    location /static/django/ {
        alias /app/backend_static/;
    }
}